image: ros:melodic-ros-base

cache:
  paths:
    - ccache/

before_script:
  - apt-get update && apt-get install -y libusb-dev ros-melodic-openslam-gmapping ros-melodic-realsense2-camera ros-melodic-rtabmap-ros ros-melodic-video-stream-opencv ros-melodic-rviz ros-melodic-rosserial ros-melodic-joystick-drivers
  
catkin_make:
  stage: build
  script:
    - catkin_make
  only:
    - merge_requests
    - master
