[supervisord]
nodaemon=true
user=root

[program:vnc]
command=/usr/bin/vncserver :1 -geometry 1920x1080 -depth 24 -SecurityTypes None -fg
user=rover
environment=USER="rover",HOME="/home/rover"
autorestart=true
priority=100

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5901
user=rover
autorestart=true
priority=200