dual_joystick_arm_controller:
  ros_parameters:
    control_mode: "dual"

    controller_1:
      type: "xbox"
      enabled: true
      joints: [1,2,3,4]

    controller_2:
      type: "logitech"
      enabled: true
      joints: [5,6]

    control_rate: 50.0
    deadzone: 0.15
    max_joint_velocity: 0.5
    trajectory_duration: 0.1

    controller_types:
      xbox:
        q1_axis: 0 # left stick x tower
        q2_axis: 1 # left stick y shoulder
        q3_axis: 4 # right stick y elbow
        q4_axis: 3 # right stick x wrist pitch

        q1_scale: 1.0
        q2_scale: 1.0
        q3_scale: 1.0
        q4_scale: 1.0
        q1_invert: false
        q2_invert: false
        q3_invert: false
        q6_invert: false

      logitech:
        q5_axis: 1 # joystick y for roll
        q6_axis: 2 # throttle gripper

        roll_cw_button: 4     # LB
        roll_ccw_button: 5    # RB

        q5_scale: 1.0
        q6_scale: 1.0
        q5_invert: false
        q6_invert: false

      #can add more controller types here        