dual_joystick_arm_controller:
  ros_parameters:
    control_mode: "single"

    controller_1:
      type: "xbox"
      enabled: true
      joints: [1,2,3,4,5,6]
    
    controller_2:
      enabled: false

    control_rate: 50.0
    deadzone: 0.15
    max_joint_velocity: 0.5
    trajectory_duration: 0.1

    controller_types:
      xbox:
        q1_axis: 0 # left stick x tower
        q2_axis: 1 # left stick y shoulder
        q3_axis: 4 # right stick y elbow
        q4_axis: 3 # right stick x wrist pitch
        q5_axis: 2 # left trigger wrist roll
        q6_axis: 5 # right trigger end effector open/close

        #We can add button controls
        gripper_open_button: 0  # A button
        gripper_close_button: 1 # B button
        roll_cw_button: 4     # LB
        roll_ccw_button: 5    # RB

        q1_scale: 1.0
        q2_scale: 1.0
        q3_scale: 1.0
        q4_scale: 1.0
        q5_scale: 1.0
        q6_scale: 1.0
        q1_invert: false
        q2_invert: false
        q3_invert: false
        q4_invert: false
        q5_invert: false
        q6_invert: false  