; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = 
	waspinator/AccelStepper@^1.64
	paulstoffregen/TimerThree
	pololu/JrkG2@^1.1.0
	arduino-libraries/Servo@^1.3.0
build_flags = 
	-I include
	-I src/comms
	-I src/drivers
	-I src/tasks
  -I src/apps

  
[env:AppRA]
build_flags = -D APP_RA
build_src_filter = +<main.cpp> +<apps/AppRA.cpp>

[env:AppGNC]
build_flags = -D APP_GNC
build_src_filter = +<main.cpp> +<apps/AppGNC.cpp>
