# This config file is used by ros2_control
controller_manager:
  ros__parameters:	
    update_rate: 20  # Hz (this changes the frequency that we serial read and write to and from the arduino as well)

    uorover_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    uorover_ee_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

uorover_arm_controller:
  ros__parameters:
    joints:
      - q1
      - q2
      - q3
      - q4
      - q5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

uorover_ee_controller:
  ros__parameters:
    joint: q6

gpio_controller:
  ros_parameters:
    type: "arm_controls/GPIOController"
    inputs:
      - stepper_1/enable
      - stepper_2/enable
      - stepper_3/enable
      - stepper_4/enable
      - laser/enable
      - full_stop/enable
