# This config file is used by ros2_control
controller_manager:
  ros__parameters:	
    update_rate: 10  # Hz (this changes the frequency that we serial read and write to and from the arduino as well)

    uorover_arm_controller: # Moveit controller for IK 
      type: joint_trajectory_controller/JointTrajectoryController

    uorover_ee_controller: #Custom controller that sends velocity data to the ee and roll joints
      type: arm_controls/GripperController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    peripheral_controller: #Enables and disables motors and lasers
      type: arm_controls/PeripheralController

uorover_arm_controller:
  ros__parameters:
    joints:
      - q1 # Tower Joint
      - q2 # Shoulder Joint
      - q3 # Elbow Joint
      - q4 # Pitch Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

uorover_ee_controller: # This is a custom controller that sends velocities from the spacemouse to the hardware interface
  ros__parameters:
    joints:  
      - q5 # Roll Joint
      - q6 # EE Joint

peripheral_controller: # Custom controller that enables and disables peripherals on the arduino, as well as stops it
  ros__parameters:
    peripherals:
      - stepper_1
      - stepper_2
      - stepper_3
      - stepper_4
      - laser
      - emergency_stop
