<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robotic_arm_controls</name>
  <version>0.1.0</version>
  <description>The robotic_arm_controls package</description>
  <maintainer email="ocaro009@uottawa.ca">Olivier Caron</maintainer>
  <maintainer email="jzhan558@uottawa.ca">Justin Zhang</maintainer>
  <license>BSD</license>
  <url type="website">
    https://gitlab.com/uorover/rover_workspace/-/wikis/Architecture-and-Design/Robotic-Arm-Software</url>

  <exec_depend>general_interfaces</exec_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>