# This is the generic central server configuration.

# Listeners for clients and the robot.
srtAddress: :9000
rtspAddress: :8554
# Explicitly set the WebRTC/Web UI port to something less common.
webrtcAddress: :8989
rtmpAddress: "" # Disabled

# THE KEY CHANGE: Use 'all' instead of a specific path name.
paths:
  all: {}
