# Modified from https://github.com/ros-drivers/usb_cam/blob/501af3d428513b2fd520b7a087ba5774b4d6181d/config/params_1.yaml
# LD ELP camera 2
# Supported resolutions: 1280x720, 800x600, 640x480, etc.
/**:
  ros__parameters:
    video_device: "/dev/v4l/by-path/platform-3610000.usb-usb-0:2.2:1.0-video-index0"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "mjpeg2rgb" # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 640
    image_height: 480
    camera_name: "ld_2"
    camera_info_url: "package://usb_cam/config/camera_info.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 100
    autofocus: false
    focus: -1
