<?xml version="1.0"?>
<package format="2">
  <name>robotic_arm_package</name>
  <version>0.1.0</version>
  <description>The Robotic Arm package</description>

  <maintainer email="ocaro009@uottawa.ca">Olivier Caron</maintainer>
  <maintainer email="jzhan558@uottawa.ca">Justin Zhang</maintainer>
  <license>BSD</license>
  <url type="website">https://gitlab.com/uorover/rover_workspace/-/wikis/Architecture-and-Design/Robotic-Arm-Software</url>

  <author email="ocaro009@uottawa.ca">Olivier Caron</author>
  <author email="jzhan558@uottawa.ca">Justin Zhang</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>

  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>

  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>

  </export>

</package>